import type { Metadata } from "next";
import { DM_Sans } from 'next/font/google';
import "./globals.css";
import localFont from 'next/font/local';

const switzer = localFont({
  src: './fonts/Switzer-Variable.woff2',
  display: 'swap',
  variable: '--font-switzer',
});


// 2. Configure it
const dmSans = DM_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '700'], // Select weights you need
  variable: '--font-dm-sans', // Name your CSS variable
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Cooked",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${switzer.variable} ${dmSans.variable}`}>
        {children}
      </body>
    </html>
  );
}


